//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AnjLab.FX.System;
using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("0.1.2848.0")]
[assembly: AssemblyFileVersion("0.1.2848.0")]
[assembly: AssemblyBuildDate("03/30/2015")]
[assembly: AssemblyCompany("AnjLab")]
[assembly: AssemblyProduct("AnjLab Sql Express Profiler")]


